### ISSUE TITLE
problem with blocking

### ISSUE THREAD

**Issue by oatly93** [AXeL-dev/distract-me-not#23]
Hi man, love your extension. Very neat!
However, it looks like I've been having some problems: if I write a website directly in the address bar, it gets blocked. If I access via google search then it doesn't. Am I doing something wrong? Maybe it has to do with the HTTPS (happened to me before in other blockers...)

### Using firefox 88.01 linux mint // other things have no idea how to check...
* version of npm
* version of node.js
* version of reactjs
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by AXeL-dev** [comment]
Hey,

> love your extension. Very neat!

Well, that's great to hear!

> if I write a website directly in the address bar, it gets blocked. If I access via google search then it doesn't. Am I doing something wrong? Maybe it has to do with the HTTPS (happened to me before in other blockers...)

Can u provide the url of the website you're testing on so i could try to reproduce that? you can even export your blocking list & send to me on my [email address](mailto:contact.axel.dev@gmail.com) (might be better to figure out what's happening).

Also, since you said the issue might be related to the HTTPS, can you check on the blocking list if the website url is prefixed with an asterisk, like so: `*.website.com`?

Have a great day!

**Comment by oatly93** [comment]
Hey again,
putting an asterisk before the address seems to have solved the issue. I'm guessing it was the HTTPs then :)
Thank you! I'm trying to combat an addiction with this ;)
Best

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
