### ISSUE TITLE
Close Tab problem when trying to add a new google account

### ISSUE THREAD

**Issue by notmyclearname** [AXeL-dev/distract-me-not#25]
Hey, love your extension but might spotted a small mistake.

### Your environment
* version of distract me not: 2.0.6
* Firefox Version: 88.0.1

### Steps to reproduce
1. Insert to Blacklist:
` *.youtube.com/*`
2. Choose default action:
Close Tab
3. Choose Black List Mode as active and save
4. Login to a google account, and try to add another Account

### Expected behaviour
Since blacklist is active and youtube isn't accessed in the described process it should be possible to add another google account without the tab closing at any time in the process

### Actual behaviour
The moment I do (4.) I get a blink of the Sign-In from google to enter an email-adress. Then the tab closes within parts of a second.

### Comment
I guess that its a fail on my side or a bug of the "close tab" option, because the other actions "block" and "redirect to website" just work fine

**Comment by AXeL-dev** [comment]
Hey, thanks for the detailed informations, i'll try to reproduce that & get back to you once i have some news.

**Comment by AXeL-dev** [comment]
Well, i can confirm the bug, most likely, the login page of google does a background request to a youtube url & the blocker detects that & decide to close the tab ? :thinking: , anyway i'll dig more deeper into that.

**Comment by AXeL-dev** [comment]
Yeah.. that's exactly what's happening (see the screenshot below)

![image](https://user-images.githubusercontent.com/30635693/120070383-2b51e180-c082-11eb-95f0-b73f1177fc26.png)

one of the possible solution could be to ignore the `accounts.youtube.com` url but this is not actually supported on the current version of the extension, i'll review the url matching process & see if it can be improved to handle this kind of cases.

**Comment by notmyclearname** [comment]
Since its my first issue to write i'm glad that I could draw your attention to that little bug, so you can have it fixed!

It actually isn't bothering me a lot, it just seemed out of place for me.
What's still out of place in my opinion is that the other actions "redirect to website" and "block" work fine, while "close tab" doesn't. So i am wondering why is that? Maybe checking that can help you fix it.

Keep up the good work!

**Comment by AXeL-dev** [comment]
> i'm glad that I could draw your attention to that little bug, so you can have it fixed!

Your first issue was really clear & precise, i give you 9/10 :laughing:.

> What's still out of place in my opinion is that the other actions "redirect to website" and "block" work fine, while "close tab" doesn't.

I agree that this looks a bit weird & confused me too at first, but after reviewing the code, it looks like "redirect to website" & "block" actions both uses redirection (to the specified website or to the blocking page url), & this redirection is not always handled the same way, it mainly depends on the triggered browser event & we handle 3 main events in the extension:
- [onBeforeRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest)
- [onUpdated](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated)
- [onReplaced](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onReplaced)

For the first event (onBeforeRequest), the redirection is automatically handled by the browser we just have to return the redirect url to the event handler, so i think that since `accounts.youtube.com` is a sub request & not the main request (accounts.google.com) on the active browser tab, the browser just ignores the redirection, while "close tab" action is in fact executed by the extension code itself & not by the browser (which makes the tab get closed). I hope that's enough clear even if it still a little ambigious i know.
PS: for the "onUpdated" & "onReplaced" events, the redirection is also handled by the extension code itself, so if the sub request event was triggered by one of these events, the redirection will be surely executed.

![screen](https://user-images.githubusercontent.com/30635693/120074245-df0f9d00-c093-11eb-8f8f-f2bf837c5224.png)

**Comment by notmyclearname** [comment]
Thank you very much! Since I'm new to this please feel free to tell me if there is something I can improve regarding my next issue.

Also thanks for the detailed explanation. It really helped understanding the core difference between "redirection"/"block" and "close tab". Good luck!

**Comment by AXeL-dev** [comment]
I finally came up with a more simple solution, which consist on adding a "combined mode" that simply combines both blacklist & whitelist modes.

Please follow the following steps to fix your issue:

**1.** Update the extension to the latest version (2.0.7).
**2.** Go to settings & change mode to "Combined".
**3.** Add the following url to your whitelist: `accounts.youtube.com/*`.

et "voilà"! xD

Also, i've added a logs list (next to settings icon), so it would be easy to know which urls get blocked & which ones passes.

**Comment by notmyclearname** [comment]
Jep that works for me. Well done!
What would be perfect is having a short explanation somewhere what "combined mode" means for you because I think it can be ambiguous. I see two possible explanations.

1. the blacklist is active and the urls that happen to be in the whitelist too get whitelisted
2. the whitelist is active blocking any other url except the ones standing in it and additionally the blacklist blacklists all urls that happen to be in both the blacklist and the whitelist

**I** know it is 1.) otherwise my issue wouldn't be solved but other users might be confused without further explanation. Maybe add a line of text that appears just when choosing "Combined" in the preferences.

Since everything is solved I will close the issue later that day :)

**Comment by AXeL-dev** [comment]
> What would be perfect is having a short explanation somewhere what "combined mode" means for you because I think it can be ambiguous. I see two possible explanations.

The 1st explanation is the more close one, the combined mode simply checks if a url isn't whitelisted before checking the blacklist.

> Maybe add a line of text that appears just when choosing "Combined" in the preferences.

Indeed, that's a good point!

> Since everything is solved I will close the issue later that day :)

Yeah sure, thanks for bringing up that issue :grin:, i think that the new combined mode would solve many other coming issues lol.

**Comment by notmyclearname** [comment]
No problem! I thought since its a very specific issue you might never discover it if I didn't told you.

And if it brings up more problems well thats what coding is all about :D
