### ISSUE TITLE
Feature Request: Remove Password Requirement to Enable Blocking

### ISSUE THREAD

**Issue by OttScott** [AXeL-dev/distract-me-not#50]
It makes little sense to require a password in order to enable the service. In current form, a user would have to type in his password, potentially having to find it, or retrieve it from a password vault, in order to turn on the blocker.
I could potentially see some edge case where the current implementation would prevent pranks when a browser is left logged in. That aside, however, I would consider the default use case as:
1) User decides he/she needs to be uninterrupted
2) Clicks Distract-Me-Not
3) Clicks Enable

Attempting to Disable the blocker outside of schedule, or any configuration changes should continue to require a password.

**Comment by AXeL-dev** [comment]
Hum, i'm not sure to get what you mean :thinking:, since the password is mainly there to protect your settings from being changed/accessed by someone else. 

Actually, we have those too options (see the screenshots below), that let you bypass the password in some cases:
![Capture d'écran Deepin_zone de sélection _20220224090837](https://user-images.githubusercontent.com/30635693/155484703-b21e2c05-033f-4b19-88c6-aab37615bc31.png)
![Capture d'écran Deepin_zone de sélection _20220224090853](https://user-images.githubusercontent.com/30635693/155484708-c8d859b1-4d56-4505-b028-3e555431e06c.png)

Still from what i understood, you're asking for a way to disable the password requirement in some other cases? like being able to enable/disable the extension without entering the password (even when pass-protection is enabled).

**Comment by AXeL-dev** [comment]
Actually, after thinking a little more about this, i'm wondering why not to add a "timer" mode:

![Capture d'écran Deepin_zone de sélection _20220224210523](https://user-images.githubusercontent.com/30635693/155599327-805fdc01-585f-4c4e-9733-8090320e800c.png)

Once you access the panel, you have a timer mode button, you click on it, you enter the amount of time for which you don't want to be disturbed, the timer starts counting & disallow you to disable the extension. Would that fit your needs?

**Comment by OttScott** [comment]
Not quite what I mean. Say I'm sitting down to work on a project and I realize I'm getting distracted. I have ADHD so I have a password which makes it harder to turn off DMN impulsively. I sit down to work on my project and click the dimmed (off) DMN icon and am prompted to enter my password.
![image](https://user-images.githubusercontent.com/14189124/155642211-3a49cc23-d6b0-4d7e-bcef-e269bd849f5b.png)
Then I have to open my password manager and find my password.
![image](https://user-images.githubusercontent.com/14189124/155642383-273d2400-c2a8-413d-9857-499e442cce21.png)
Now that I can unlock DMN, I can finally get in and turn on the don't distract me I'm hoping for.
![image](https://user-images.githubusercontent.com/14189124/155643351-48b25360-0ace-4ec5-87cc-4e9a46d19ed4.png)

What I'm suggesting is that password would only be required if DMN is Active or to open Config. Perhaps as you've designed it, changing modes would prompt also. But if it is not in block mode, please allow me to easily switch it on so I don't get distracted until I switch it on.  🤣

I do think your timer idea is also a great feature. You could enable timer and see the countdown (without password) from clicking the icon, but can't disable it or change config until you supply the password. Kind of like an 'Are you sure?' button...

**Comment by AXeL-dev** [comment]
How about this:

![Capture d'écran Deepin_zone de sélection _20220225124150](https://user-images.githubusercontent.com/30635693/155711396-1a3b596c-35fc-40b4-9aca-c7c1fcc2bacf.png)

![Peek 25-02-2022 12-54](https://user-images.githubusercontent.com/30635693/155711409-b1fa983c-1745-4e35-9895-1ee4c42195cc.gif)

**Comment by OttScott** [comment]
Perfect!

**Comment by AXeL-dev** [comment]
Deployed in version `2.6.2` (might need to wait for few days until it gets published).
